# keywords
📋: class
📦: module
🔜: def
🔚: end
🚣: self
✋: yield
⛔️: private
👉: "->"
🔨: do
➿: loop
🎡: while

# symbols
💬: "\""
▪️: "."
↪️: "("
↩️: ")"
➰: ","

# conveniences
👀: puts
🐣: new
💥: raise
➕: +
🚰: tap
📞: call
⚠️: warn
